// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: proto/watcher.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Runtime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Found         bool                   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runtime) Reset() {
	*x = Runtime{}
	mi := &file_proto_watcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runtime) ProtoMessage() {}

func (x *Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runtime.ProtoReflect.Descriptor instead.
func (*Runtime) Descriptor() ([]byte, []int) {
	return file_proto_watcher_proto_rawDescGZIP(), []int{0}
}

func (x *Runtime) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Runtime) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Runtime) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Runtime) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Kernel        string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_proto_watcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_proto_watcher_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

type ObserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeFilter []string               `protobuf:"bytes,1,rep,name=runtime_filter,json=runtimeFilter,proto3" json:"runtime_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_proto_watcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_proto_watcher_proto_rawDescGZIP(), []int{2}
}

func (x *ObserveRequest) GetRuntimeFilter() []string {
	if x != nil {
		return x.RuntimeFilter
	}
	return nil
}

type ObserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtimes      []*Runtime             `protobuf:"bytes,1,rep,name=runtimes,proto3" json:"runtimes,omitempty"`
	SystemInfo    *SystemInfo            `protobuf:"bytes,2,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveResponse) Reset() {
	*x = ObserveResponse{}
	mi := &file_proto_watcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveResponse) ProtoMessage() {}

func (x *ObserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveResponse.ProtoReflect.Descriptor instead.
func (*ObserveResponse) Descriptor() ([]byte, []int) {
	return file_proto_watcher_proto_rawDescGZIP(), []int{3}
}

func (x *ObserveResponse) GetRuntimes() []*Runtime {
	if x != nil {
		return x.Runtimes
	}
	return nil
}

func (x *ObserveResponse) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

func (x *ObserveResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_watcher_proto protoreflect.FileDescriptor

const file_proto_watcher_proto_rawDesc = "" +
	"\n" +
	"\x13proto/watcher.proto\x12\awatcher\"a\n" +
	"\aRuntime\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\"P\n" +
	"\n" +
	"SystemInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\"7\n" +
	"\x0eObserveRequest\x12%\n" +
	"\x0eruntime_filter\x18\x01 \x03(\tR\rruntimeFilter\"\x93\x01\n" +
	"\x0fObserveResponse\x12,\n" +
	"\bruntimes\x18\x01 \x03(\v2\x10.watcher.RuntimeR\bruntimes\x124\n" +
	"\vsystem_info\x18\x02 \x01(\v2\x13.watcher.SystemInfoR\n" +
	"systemInfo\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2V\n" +
	"\x0eWatcherService\x12D\n" +
	"\x0fObserveRuntimes\x12\x17.watcher.ObserveRequest\x1a\x18.watcher.ObserveResponseB$Z\"github.com/binaryarc/watcher/protob\x06proto3"

var (
	file_proto_watcher_proto_rawDescOnce sync.Once
	file_proto_watcher_proto_rawDescData []byte
)

func file_proto_watcher_proto_rawDescGZIP() []byte {
	file_proto_watcher_proto_rawDescOnce.Do(func() {
		file_proto_watcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_watcher_proto_rawDesc), len(file_proto_watcher_proto_rawDesc)))
	})
	return file_proto_watcher_proto_rawDescData
}

var file_proto_watcher_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_watcher_proto_goTypes = []any{
	(*Runtime)(nil),         // 0: watcher.Runtime
	(*SystemInfo)(nil),      // 1: watcher.SystemInfo
	(*ObserveRequest)(nil),  // 2: watcher.ObserveRequest
	(*ObserveResponse)(nil), // 3: watcher.ObserveResponse
}
var file_proto_watcher_proto_depIdxs = []int32{
	0, // 0: watcher.ObserveResponse.runtimes:type_name -> watcher.Runtime
	1, // 1: watcher.ObserveResponse.system_info:type_name -> watcher.SystemInfo
	2, // 2: watcher.WatcherService.ObserveRuntimes:input_type -> watcher.ObserveRequest
	3, // 3: watcher.WatcherService.ObserveRuntimes:output_type -> watcher.ObserveResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_watcher_proto_init() }
func file_proto_watcher_proto_init() {
	if File_proto_watcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_watcher_proto_rawDesc), len(file_proto_watcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_watcher_proto_goTypes,
		DependencyIndexes: file_proto_watcher_proto_depIdxs,
		MessageInfos:      file_proto_watcher_proto_msgTypes,
	}.Build()
	File_proto_watcher_proto = out.File
	file_proto_watcher_proto_goTypes = nil
	file_proto_watcher_proto_depIdxs = nil
}
